import { fromHtml } from 'hast-util-from-html';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkMath from 'remark-math';
import remarkRehype from 'remark-rehype';
import rehypeKatex from 'rehype-katex';
import katex from 'katex';
import { ansiToHast } from './ansi.mjs';

export const mimePriority = [
  'application/vnd.plotly.v1+json', 'text/html', 'text/markdown',
  'image/svg+xml', 'text/latex', 'image/png', 'image/jpeg', 'text/plain',
];
/** @returns {import('hast').Element} */
const element = (tagName, properties, children) => ({ type: 'element', tagName, properties, children });
/** @returns {import('hast').Text} */
const text = (value) => ({ type: 'text', value });
const string = (value) => Array.isArray(value) ? value.join('') : String(value);
const html = (value) => fromHtml(value, { fragment: true }).children;
const markdown = unified().use(remarkParse).use(remarkMath).use(remarkRehype).use(rehypeKatex);

/** Render one Jupyter output; inline results (from {eval}) stay in the surrounding sentence. */
export async function renderOutput(output, { inline = false } = {}) {
  let children;
  let mime;
  if (inline) {
    mime = mimePriority.find((type) => Object.hasOwn(output.data ?? {}, type));
    if (!mime || mime === 'application/vnd.plotly.v1+json') throw new Error(`Unsupported inline Jupyter MIME bundle: ${Object.keys(output.data ?? {}).join(', ')}`);
    const value = string(output.data[mime]);
    if (mime === 'text/html' || mime === 'image/svg+xml') children = html(value);
    else if (mime === 'text/markdown') {
      const rendered = (await markdown.run(markdown.parse(value))).children.filter(child => child.type !== 'text' || child.value.trim());
      children = rendered.length === 1 && rendered[0].tagName === 'p' ? rendered[0].children : rendered;
    } else if (mime === 'text/latex') {
      children = html(katex.renderToString(value.trim().replace(/^\$\$?|\$\$?$/g, '').replace(/^\\\(|\\\)$/g, ''), { displayMode: false, throwOnError: true }));
    } else if (mime.startsWith('image/')) {
      children = [element('img', { src: `data:${mime};base64,${value.replace(/\s/g, '')}`, alt: output.metadata?.[mime]?.alt ?? 'Inline figure' }, [])];
    } else children = [text(value)];
    return element('span', { className: ['jupyter-output', 'jupyter-inline'], dataMime: mime, dataSourceGenerated: 'true' }, children);
  }
  if (output.output_type === 'stream') {
    mime = output.name;
    children = [element('pre', {}, [text(string(output.text))])];
  } else if (output.output_type === 'error') {
    // Only cells tagged raises-exception reach this point: the build otherwise fails.
    mime = 'application/vnd.jupyter.error';
    const traceback = output.traceback?.length ? output.traceback.join('\n') : `${output.ename}: ${output.evalue}`;
    children = [element('pre', { className: ['jupyter-error'] }, ansiToHast(traceback))];
  } else {
    mime = mimePriority.find((type) => Object.hasOwn(output.data ?? {}, type));
    if (!mime) throw new Error(`Unsupported Jupyter MIME bundle: ${Object.keys(output.data ?? {}).join(', ')}`);
    const value = output.data[mime];
    if (mime === 'application/vnd.plotly.v1+json') {
      children = [element('div', {
        className: ['jupyter-plotly'], dataPlotly: JSON.stringify(value),
        role: 'img', ariaLabel: 'Interactive plot; hover for values and drag to zoom',
      }, [])];
    } else if (mime === 'text/html' || mime === 'image/svg+xml') {
      children = html(string(value));
    } else if (mime === 'text/markdown') {
      children = (await markdown.run(markdown.parse(string(value)))).children;
    } else if (mime === 'text/latex') {
      const expression = string(value).trim().replace(/^\$\$?|\$\$?$/g, '').replace(/^\\\[|\\\]$/g, '');
      children = html(katex.renderToString(expression, { displayMode: true, throwOnError: true }));
    } else if (mime.startsWith('image/')) {
      children = [element('img', {
        src: `data:${mime};base64,${string(value).replace(/\s/g, '')}`,
        alt: output.metadata?.[mime]?.alt ?? 'Figure generated by the preceding code cell',
      }, [])];
    } else {
      children = [element('pre', {}, [text(string(value))])];
    }
  }
  return element('div', { className: ['jupyter-output'], dataMime: mime }, children);
}

export function rehypeJupyter() {
  return async (tree) => {
    async function replace(parent) {
      for (let i = 0; i < (parent.children?.length ?? 0); i++) {
        const child = parent.children[i];
        if (child.type === 'element' && child.tagName === 'jupyter-output') {
          parent.children[i] = await renderOutput(child.properties.bundle, { inline: Boolean(child.properties.inline) });
        } else await replace(child);
      }
    }
    await replace(tree);
  };
}
