import { fromHtml } from 'hast-util-from-html';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkMath from 'remark-math';
import remarkRehype from 'remark-rehype';
import rehypeKatex from 'rehype-katex';
import katex from 'katex';

export const mimePriority = [
  'application/vnd.plotly.v1+json', 'text/html', 'text/markdown',
  'image/svg+xml', 'text/latex', 'image/png', 'image/jpeg', 'text/plain',
];
/** @returns {import('hast').Element} */
const element = (tagName, properties, children) => ({ type: 'element', tagName, properties, children });
/** @returns {import('hast').Text} */
const text = (value) => ({ type: 'text', value });
const string = (value) => Array.isArray(value) ? value.join('') : String(value);
const html = (value) => fromHtml(value, { fragment: true }).children;
const markdown = unified().use(remarkParse).use(remarkMath).use(remarkRehype).use(rehypeKatex);

export async function renderOutput(output) {
  let children;
  let mime;
  if (output.output_type === 'stream') {
    mime = output.name;
    children = [element('pre', {}, [text(string(output.text))])];
  } else {
    mime = mimePriority.find((type) => Object.hasOwn(output.data ?? {}, type));
    if (!mime) throw new Error(`Unsupported Jupyter MIME bundle: ${Object.keys(output.data ?? {}).join(', ')}`);
    const value = output.data[mime];
    if (mime === 'application/vnd.plotly.v1+json') {
      children = [element('div', {
        className: ['jupyter-plotly'], dataPlotly: JSON.stringify(value),
        role: 'img', ariaLabel: 'Interactive plot; hover for values and drag to zoom',
      }, [])];
    } else if (mime === 'text/html' || mime === 'image/svg+xml') {
      children = html(string(value));
    } else if (mime === 'text/markdown') {
      children = (await markdown.run(markdown.parse(string(value)))).children;
    } else if (mime === 'text/latex') {
      const expression = string(value).trim().replace(/^\$\$?|\$\$?$/g, '').replace(/^\\\[|\\\]$/g, '');
      children = html(katex.renderToString(expression, { displayMode: true, throwOnError: true }));
    } else if (mime.startsWith('image/')) {
      children = [element('img', {
        src: `data:${mime};base64,${string(value).replace(/\s/g, '')}`,
        alt: output.metadata?.[mime]?.alt ?? 'Figure generated by the preceding code cell',
      }, [])];
    } else {
      children = [element('pre', {}, [text(string(value))])];
    }
  }
  return element('div', { className: ['jupyter-output'], dataMime: mime }, children);
}

export function rehypeJupyter() {
  return async (tree) => {
    async function replace(parent) {
      for (let i = 0; i < (parent.children?.length ?? 0); i++) {
        const child = parent.children[i];
        if (child.type === 'element' && child.tagName === 'jupyter-output') {
          parent.children[i] = await renderOutput(child.properties.bundle);
        } else await replace(child);
      }
    }
    await replace(tree);
  };
}
